# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: abduelmorsi/jdmzn

media_folder: public/images/posts
public_folder: /images/posts

output:
  omit_empty_optional_fields: true

collections:
  - name: posts
    label: التدوينات
    label_singular: تدوينة
    folder: src/content/posts
    format: yaml-frontmatter
    slug: '{{fields._slug}}'
    thumbnail: coverImage
    sortable_fields: [publishDate, title]
    preview_path: '/blog/{{filename}}'
    fields:
      - { name: title, label: العنوان, widget: string }
      - { name: description, label: الوصف, widget: text }
      - name: publishDate
        label: تاريخ النشر
        widget: datetime
        type: date
        input_timezone: utc
        default: '{{now}}'
      - { name: coverImage, label: صورة الغلاف, widget: image, required: false }
      - { name: body, label: المحتوى, widget: richtext }
